src/main/java/com/example/banthing/BanThingApplication.java
src/main/java/com/example/banthing/domain/chat/entity/ChatMessage.java
src/main/java/com/example/banthing/domain/chat/entity/Chatroom.java
src/main/java/com/example/banthing/domain/item/entity/CleaningDetail.java
src/main/java/com/example/banthing/domain/item/entity/Hashtag.java
src/main/java/com/example/banthing/domain/item/entity/Item.java
src/main/java/com/example/banthing/domain/item/entity/ItemImg.java
src/main/java/com/example/banthing/domain/item/entity/ItemStatus.java
src/main/java/com/example/banthing/domain/item/entity/ItemType.java
src/main/java/com/example/banthing/domain/user/entity/LoginType.java
src/main/java/com/example/banthing/domain/user/entity/User.java
src/main/java/com/example/banthing/global/common/ApiResponse.java
src/main/java/com/example/banthing/global/common/Timestamped.java
src/main/java/com/example/banthing/global/common/exception/ApiExceptionHandler.java

> #1 
> 엔티티를 추가하였습니다. 
1. createdAt, updatedAt (생성, 수정 시간) 은 Timestamped 추상 클래스로 분리하였습니다.
2. LoginType, ItemStatus, ItemType 은 enum 으로 만들었습니다.
3. cascade 설정은 하지 않았습니다.
4. 도메인형으로 디렉토리 구조를 사용하였습니다. 그에 따라 크게 domain 과 global 로 구분하였고, domain 안에 chat, item, user 패키지를 생성하였습니다.
5. 채팅 메시지를 생성, 상품 이미지 생성할 때, 연관관계 편의 메소드를 호출하여, 연관관계를 설정하도록 하였습니다.
> 공통응답 포맷을 위한 코드 추가하였습니다.
> 1. 연관관계 매핑한 부분을 잘 확인해주세요.
> 2. 추가할 필드 혹은 수정할 필드가 있으면 알려주세요.
> 3. 도메인을 크게 chat, item, user 으로 분리하였는데, 이부분에 있어서 다른 의견있으면 알려주세요.

[FEAT] 엔티티 생성

---

dockerfile
dockerfilejava

cicd: set up dockerfiles

---

.github/workflows/github_actions.yml

> ex) #11 
> main branch에 push될 때에만 github action이 trigger되도록 설정했습니다.

[CICD] Trigger on main branch

---

src/main/java/com/example/banthing/domain/user/controller/KakaoController.java
src/main/java/com/example/banthing/domain/user/controller/UserController.java
src/main/java/com/example/banthing/domain/user/dto/ProfileResponseDto.java
src/main/java/com/example/banthing/domain/user/dto/PurchaseResponseDto.java
src/main/java/com/example/banthing/domain/user/dto/SalesResponseDto.java
src/main/java/com/example/banthing/domain/user/dto/UpdateAddressRequestDto.java
src/main/java/com/example/banthing/domain/user/dto/UpdateAddressResponseDto.java
src/main/java/com/example/banthing/domain/user/dto/UpdateNicknameRequestDto.java
src/main/java/com/example/banthing/domain/user/dto/UpdateProfileResponseDto.java
src/main/java/com/example/banthing/domain/user/entity/ProfileImage.java
src/main/java/com/example/banthing/domain/user/entity/User.java
src/main/java/com/example/banthing/domain/user/repository/ProfileRepository.java
src/main/java/com/example/banthing/domain/user/service/KakaoService.java
src/main/java/com/example/banthing/domain/user/service/UserService.java
src/main/java/com/example/banthing/global/config/SecurityConfig.java

> #7
> 유저와 관련된 api 구현
1. 프로필(이름, 사진) 수정
2. 프로필 조회
3. 구매 목록 및 판매 목록 조회
4. 위치 등록 및 수정
> 프로필 이미지는 ProfileImage 로 분리하였습니다.

[FEEAT] 유저 관련 기능

---

src/main/java/com/example/banthing/domain/user/controller/ProfileController.java
src/main/java/com/example/banthing/domain/user/service/ProfileService.java

[FEAT] 프로필 이미지 등록

---

src/main/java/com/example/banthing/domain/item/entity/CleaningDetail.java
src/main/java/com/example/banthing/domain/item/entity/Hashtag.java
src/main/java/com/example/banthing/domain/item/entity/Item.java
src/main/java/com/example/banthing/domain/item/repository/CleaningDetailRepository.java
src/main/java/com/example/banthing/domain/item/repository/HashtagRepository.java
src/main/java/com/example/banthing/domain/item/repository/ItemImgsRepository.java
src/main/java/com/example/banthing/domain/item/repository/ItemRepository.java

> #6 
> 아이템 엔티티 및 레포지토리를 추가하였습니다.
- 아이템과 해시태그 관계를 일대다 관계로 수정하였습니다.

[FEAT] 아이템 엔티티 및 레포지토리

---

src/main/java/com/example/banthing/domain/item/dto/ItemDto.java
src/main/java/com/example/banthing/domain/item/service/HashtagService.java
src/main/java/com/example/banthing/domain/item/service/ItemService.java

> #6
> 상품 삭제 기능 구현 (item과 item관련 엔티티들 전부 삭제입니다) 
> 상품 단건 조회 수정

feat: 상품 삭제 구현, 상품 단건 조회 수정

---

.github/workflows/github_actions.yml

> ex) #28 
> cicd 테스트 진행하겠습니다.

cicd: 테스트1

---

src/main/java/com/example/banthing/global/config/WebConfig.java

> #31 
> cors 설정을 위한 WebConfig 파일을 추가하였습니다.
https://hoehen-flug.tistory.com/58

[FEAT] cors 설정

---

src/main/java/com/example/banthing/domain/item/service/ItemService.java

> ex) #34 
> 코드 에러 수정했습니다
> 기현님:::: pull 한번 더 받으시고 그래들 추가한 코드 푸쉬해주세요

fix: 코드에러 수정

---

.github/workflows/github_actions.yml

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

fix: yml 수정

---

src/main/java/com/example/banthing/global/config/SecurityConfig.java

[BUG] 로그인 실패

---

src/main/java/com/example/banthing/global/config/SecurityConfig.java

> 파비콘 관련된 403 에러 발생하여 정적 리소스에 대한 접근을 허용하도로 수정하였습니다.

[BUG] 정적 리소스에 대한 접근을 허용

---

src/main/java/com/example/banthing/global/config/SecurityConfig.java

[BUG] CSRF 보호 비활성화

---

src/main/java/com/example/banthing/domain/user/controller/KakaoController.java
src/main/java/com/example/banthing/domain/user/dto/KakaoLoginResponseDto.java
src/main/java/com/example/banthing/domain/user/dto/SignUpResponseDto.java
src/main/java/com/example/banthing/domain/user/service/KakaoService.java
src/main/java/com/example/banthing/global/common/ApiResponse.java

-## 📝작업 내용
> 로그인과 회원가입을 구분하기 위한 성공 메시지를 추가하여 반환하도록 수정하였습니다.

[FEAT] 로그인/회원가입 성공 메시지

---

src/main/java/com/example/banthing/domain/user/controller/KakaoController.java
src/main/java/com/example/banthing/domain/user/service/KakaoService.java

> 크로스 도메인에서 쿠키 전달을 위해 SameSite 속성을 추가

[BUG] 쿠키 전달 오류

---

.github/workflows/github_actions.yml

> ex) #10 
> build reference를 main으로 변경

[fix]: docker fix

---

.gitignore

> ex) #54 
> .gitignore github_actions.yml 추가

[cicd] .gitignore github_actions.yml 추가

---

src/main/java/com/example/banthing/domain/user/controller/KakaoController.java
src/main/java/com/example/banthing/global/security/JwtAuthenticationFilter.java
src/main/java/com/example/banthing/global/security/JwtUtil.java

[FEAT] 토큰 헤더에 저장

---

src/main/java/com/example/banthing/domain/user/controller/UserController.java
src/main/java/com/example/banthing/domain/user/service/UserService.java

> 프로필 수정 시 변경할 값을 모두 formData 로 받도록 수정

[FEAT] 프로필 수정 시 요청 데이터 타입 변경

---

src/main/java/com/example/banthing/domain/item/controller/ItemController.java
src/main/java/com/example/banthing/domain/item/dto/CreateItemRequestDto.java
src/main/java/com/example/banthing/domain/item/service/ItemService.java

> 아이템 등록시 요청 값을 formData 로 받도록 수정

[FIX] 아이템 등록시 요청 값 타입 수정

---

src/main/java/com/example/banthing/domain/item/controller/ItemController.java
src/main/java/com/example/banthing/domain/item/dto/ItemDto.java
src/main/java/com/example/banthing/domain/item/service/ItemService.java

> #6 
> 상품 수정 API 입력값 변경
> item 수정, 삭제, 판매 완료 시 해당 item이 user의 item인지 검증하는 로직 추가, 상품 단건 조회에서 item이 존재하는지 검증하는 로직 추가

feat: 상품 수정 API 입력값 변경, 아이템 검증 로직 추가

---

src/main/java/com/example/banthing/domain/chat/controller/ChatController.java
src/main/java/com/example/banthing/domain/chat/dto/CreateRoomResponseDto.java
src/main/java/com/example/banthing/domain/chat/service/ChatroomService.java

> 채팅방 생성시 메시지와 함께 반환됩니다.
이미 방이 존재합니다. 또는 새로운 방이 생성되었습니다.

[FEAT] 채팅방 생성시 메시지와 함께 반환

---

src/main/java/com/example/banthing/domain/chat/dto/FindMessageAndItemResponseDto.java
src/main/java/com/example/banthing/domain/chat/service/ChatroomService.java

> 채팅방 조회시 판매자 이름을 포함하여 반환하도록 수정하였습니다.

[FEAT] 채팅방 조회시 판매자 이름 반환

---

src/main/java/com/example/banthing/global/common/ApiResponse.java
src/main/java/com/example/banthing/global/security/JwtAuthenticationFilter.java

> 토큰 만료시 `invalid-token` 상태 반환

[FEAT] 토큰 만료 상태 추가

---

.github/workflows/github_actions.yml

> ex) #64 
> spring, react에 ssl 적용시켰습니다. 혹시 에러 발견되는 부분 있으면 바로 전달주세요. 참고로 spring 내에 corsConfiguration은 삭제했습니다.

[test] 서버 수정 main test

---

src/main/java/com/example/banthing/domain/chat/dto/FindRoomsResponseDto.java

> 채팅 목록 조회 시 상품의 첫번째 이미지를 반환합니다.

[FEAT] 채팅 목록 조회 시 상품 이미지 반환

---

.github/workflows/github_actions.yml

> ex) #30 
> github_actions가 main에서 정상적으로 돌아가도록 수정합니다.

[fix] github_actions 수정

---

.github/workflows/github_actions.yml
src/main/java/com/example/banthing/domain/item/controller/ItemController.java
src/main/java/com/example/banthing/domain/item/service/ItemService.java

> ex) #73 
> 삭제 기능에서 cleaning_detail_id가 아닌 item_id로 cleaning details 테이블 아이템을 지우던 버그 수정

73 err fix

---

src/main/java/com/example/banthing/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/example/banthing/domain/chat/repository/ChatroomRepository.java
src/main/java/com/example/banthing/domain/chat/service/ChatroomService.java
src/main/java/com/example/banthing/domain/item/controller/ItemController.java
src/main/java/com/example/banthing/domain/item/dto/ItemDto.java
src/main/java/com/example/banthing/domain/item/service/ItemImgService.java
src/main/java/com/example/banthing/domain/item/service/ItemService.java

[fix] 오류 수정

---

.github/workflows/github_actions.yml
src/main/java/com/example/banthing/domain/item/service/ItemService.java

feat: CleaningDetail 오류 수정

---

src/main/java/com/example/banthing/domain/item/entity/Item.java

> Item 판매 완료 api 시 createdAt와 updaedAt이 동시에 update되는 오류
> createdAt 오류 수정

feat: createdAt 오류 수정

---

src/main/java/com/example/banthing/domain/item/dto/ItemDto.java

> #82 
> 아이템 단건조회 시 itemStatus 추가

feat(items) : 아이템 단건조회 시 itemStatus 추가

---

src/main/java/com/example/banthing/domain/user/dto/ProfileResponseDto.java

fix(user) : 마이프로필 조회 시 닉네임 길이 수정

---

.github/workflows/github_actions.yml
python/main__.py
python/test.py
src/main/java/com/example/banthing/domain/chat/controller/ChatController.java
src/main/java/com/example/banthing/domain/chat/websocket/WebSocketConfig.java
src/main/java/com/example/banthing/domain/item/controller/ItemController.java
src/main/java/com/example/banthing/domain/item/dto/FlaskItemResponseDto.java
src/main/java/com/example/banthing/domain/item/dto/ItemSearchResponseDto.java
src/main/java/com/example/banthing/domain/item/mapper/ItemMapper.java
src/main/java/com/example/banthing/domain/user/entity/User.java
src/main/java/com/example/banthing/domain/user/service/KakaoService.java

78 server aws

---

.github/workflows/github_actions.yml

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[fix] gitaction 수정

---

src/main/java/com/example/banthing/domain/user/controller/UserController.java
src/main/java/com/example/banthing/domain/wishlist/controller/WishlistController.java
src/main/java/com/example/banthing/domain/wishlist/dto/WishlistResponseDTO.java
src/main/java/com/example/banthing/domain/wishlist/entity/UserWishlist.java
src/main/java/com/example/banthing/domain/wishlist/repository/WishlistRepository.java
src/main/java/com/example/banthing/domain/wishlist/service/WishlistService.java

> 찜 기능 추가(찜 추가, 찜 삭제, 찜 목록 조회)

feat(user) : 찜 기능 추가(찜 추가, 찜 삭제, 찜 목록 조회)

---

src/main/java/com/example/banthing/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/example/banthing/domain/chat/repository/ChatroomRepository.java
src/main/java/com/example/banthing/domain/chat/service/ChatMessageService.java
src/main/java/com/example/banthing/domain/chat/service/ChatroomService.java
src/main/java/com/example/banthing/domain/item/controller/ItemController.java
src/main/java/com/example/banthing/domain/item/repository/ItemRepository.java
src/main/java/com/example/banthing/domain/item/service/ItemService.java
src/main/java/com/example/banthing/domain/user/controller/UserController.java
src/main/java/com/example/banthing/domain/user/dto/UserDeletionRequestDto.java
src/main/java/com/example/banthing/domain/user/entity/UserDeletionReason.java
src/main/java/com/example/banthing/domain/user/repository/UserDeletionReasonRepository.java
src/main/java/com/example/banthing/domain/user/service/UserDeletionReasonService.java
src/main/java/com/example/banthing/domain/user/service/UserService.java
src/main/java/com/example/banthing/domain/wishlist/repository/WishlistRepository.java
src/main/java/com/example/banthing/domain/wishlist/service/WishlistService.java

feat(user) : 회원 탈퇴

---

src/main/java/com/example/banthing/domain/item/dto/ItemDto.java
src/main/java/com/example/banthing/domain/item/service/ItemService.java

feat(item) : 유저 닉네임 길이 수정

---

.github/workflows/github_actions.yml

> ex) #97 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[FIX] github action 수정

---

src/main/java/com/example/banthing/admin/controller/AdminController.java
src/main/java/com/example/banthing/admin/dto/AdminReportResponseDto.java
src/main/java/com/example/banthing/admin/dto/AdminUserDeletionResponseDto.java
src/main/java/com/example/banthing/admin/dto/AdminUserResponseDto.java
src/main/java/com/example/banthing/admin/dto/CleaningDetailDto.java
src/main/java/com/example/banthing/admin/service/AdminService.java
src/main/java/com/example/banthing/domain/item/entity/ItemReport.java
src/main/java/com/example/banthing/domain/item/repository/ItemReportRepository.java
src/main/java/com/example/banthing/domain/item/repository/ReportQueryRepository.java
src/main/java/com/example/banthing/domain/item/repository/ReportQueryRepositoryImpl.java
src/main/java/com/example/banthing/domain/item/service/ItemReportService.java
src/main/java/com/example/banthing/domain/item/service/ItemService.java
src/main/java/com/example/banthing/domain/user/entity/User.java
src/main/java/com/example/banthing/domain/user/entity/UserDeletionReason.java
src/main/java/com/example/banthing/domain/user/repository/UserDeletionReasonQueryRepository.java
src/main/java/com/example/banthing/domain/user/repository/UserDeletionReasonQueryRepositoryImpl.java
src/main/java/com/example/banthing/domain/user/repository/UserDeletionReasonRepository.java
src/main/java/com/example/banthing/domain/user/repository/UserQueryRepositoryImpl.java
src/main/java/com/example/banthing/domain/user/service/KakaoService.java
src/main/java/com/example/banthing/domain/user/service/UserDeletionReasonService.java
src/main/java/com/example/banthing/domain/user/service/UserService.java

> 신고내역, 탈퇴내역 api 추가
>계정관리api에 신고내역 상세보기 데이터 추가

feat(Admin) : 신고내역, 탈퇴내역 api 추가

---

.github/workflows/github_actions.yml

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

github_action 수정

---

src/main/java/com/example/banthing/admin/controller/AdminController.java
src/main/java/com/example/banthing/admin/service/AdminService.java
src/main/java/com/example/banthing/domain/user/controller/UserController.java
src/main/java/com/example/banthing/domain/user/entity/RejoinRestriction.java
src/main/java/com/example/banthing/domain/user/entity/User.java
src/main/java/com/example/banthing/domain/user/repository/RejoinRestrictionRepository.java
src/main/java/com/example/banthing/domain/user/service/KakaoService.java
src/main/java/com/example/banthing/domain/user/service/RejoinRestrictionService.java
src/main/java/com/example/banthing/global/common/ApiResponse.java

> 계정관리(계정정지, 활성화), 탈퇴내역(재가입 제한) API 구현

feat(Admin) : 계정관리(계정정지, 활성화), 탈퇴내역(재가입 제한) API 구현

---

src/main/java/com/example/banthing/admin/controller/AdminController.java
src/main/java/com/example/banthing/admin/service/AdminService.java
src/main/java/com/example/banthing/domain/item/repository/ReportQueryRepository.java
src/main/java/com/example/banthing/domain/item/repository/ReportQueryRepositoryImpl.java
src/main/java/com/example/banthing/domain/item/service/ItemReportService.java
src/main/java/com/example/banthing/domain/user/entity/User.java

109 feat 회원 탈퇴 계정 정지 활성화

---

src/main/java/com/example/banthing/domain/user/entity/UserReport.java
src/main/java/com/example/banthing/domain/user/repository/UserReportRepository.java
src/main/java/com/example/banthing/domain/user/service/UserReportService.java
src/main/java/com/example/banthing/domain/user/service/UserService.java

> 신고하거나 신고당했을 시 회원탈퇴 안되는 오류 수정

fix(User) : 회원탈퇴 수정

---

src/main/java/com/example/banthing/domain/item/repository/ItemReportRepository.java
src/main/java/com/example/banthing/domain/item/service/ItemReportService.java
src/main/java/com/example/banthing/domain/user/service/UserService.java

fix(User) : 회원탈퇴 수정(아이템 신고기록2)
